### ISSUE TITLE
Use confidential client for authorization

### ISSUE THREAD

**Issue by TheSlimvReal** [Aam-Digital/account-backend#3]
A confidential client allows authentication via a constant secret that can be used with the Keycloak NodeJS library.
On the client a set of permissions can be defined for the different resources, in this case the account operations.
This setup would have to be part of the provided docker image in [ndb-setup](https://github.com/Aam-Digital/ndb-setup).

**Comment by TheSlimvReal** [comment]
Can be accomplished through [nest-keycloak-connect](https://www.npmjs.com/package/nest-keycloak-connect)

**Comment by TheSlimvReal** [comment]
There is a library which would help a lot with the general setup and permissions [nest-keylcoak-connect](https://www.npmjs.com/package/nest-keycloak-connect)

**Comment by sleidig** [comment]
won't fix (long-term will migrate to aam-services, see #26 )
